name: color_picker_palette
description: A color picker which you are looking for.
version: 0.1.3
author: vemarav <vemaravv@gmail.com>
homepage: https://github.com/vemarav

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter